default:
  owner: config-service
  content: spring cloud test config-service 

spring:
  profiles:
    active: test 

  datasource:
    driver: com.h2.Driver
    url: dbUrl
    username: admin
    password: admin

token:
  key: jwt_token_value
