spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver: com.h2.Driver
    url: dbUrl
    username: admin
    password: admin

default:
  message: user-service 에서 default profiles 에서 사용할 설정 정보

token:
  key: "default_jwt_token_value"
  # key: jwt_token_value

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver: com.h2.Driver
    url: dbUrl
    username: dev
    password: dev

default:
  message: user-service 에서 dev profiles 에서 사용할 설정 정보

token:
  key: "{cipher}5202377763cbdbc6cfbc7ecc5105d8b2b1b4af3f28ca713cb84e675e0729adcf82152462ce8276a32976da4a666017e6"

---

spring:
  config:
    activate:
      on-profile: test

  datasource:
    driver: com.h2.Driver
    url: dbUrl
    username: test
    password: test


default:
  message: user-service 에서 test profiles 에서 사용할 설정 정보

token:
  key: "{cipher}5202377763cbdbc6cfbc7ecc5105d8b2b1b4af3f28ca713cb84e675e0729adcf82152462ce8276a32976da4a666017e6"

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver: com.h2.Driver
    url: dbUrl
    username: prod
    password: prod

default:
  message: user-service 에서 prod profiles 에서 사용할 설정 정보

token:
  key: "{cipher}5202377763cbdbc6cfbc7ecc5105d8b2b1b4af3f28ca713cb84e675e0729adcf82152462ce8276a32976da4a666017e6"
