
server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: health, beans, refresh , busrefresh  

spring:
  application:
    name: config-service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest


# local file 연결 - # local-msa-config 테스트시 주석 해제     
#  profiles:
#    active: native
#        
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: /workspace/devwork/spring-cloud-msa-study/msa/local-msa-config  # file://${user.home}/외부-설정-파일-경로
         
#  git 저장소 연결   
  cloud:
    config:
      server:
        git:
          uri: https://github.com/devsunset/spring-cloud-msa-study
#          username: 
#          password: 




 